name: battleship_game
description: Flutter miniproject that runs 1-player battleship game.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  http: ^0.13.5
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
